import type { Defect, HistoricalDefect } from "./triage-types";

export const incomingDefects: Defect[] = [
  {
    id: "PAY-1842",
    title: "Checkout payment fails after OTP confirmation",
    description:
      "Customers can enter card details and OTP, but after confirmation the checkout page shows a generic error. Orders are not created.",
    environment: "Production",
    area: "Payments",
    reporter: "Anika QA",
    logs: "POST /payment/authorize 502 gateway timeout. provider_ref missing. impact: multiple users.",
  },
  {
    id: "AUTH-771",
    title: "Password reset link opens blank page on Safari",
    description:
      "Reset email is generated successfully. On Safari 17 the reset URL opens a blank screen after the token validation call.",
    environment: "UAT",
    area: "Identity",
    reporter: "Rahul QE",
    logs: "TypeError: crypto.subtle undefined during reset-token verify. No production impact yet.",
  },
  {
    id: "INV-409",
    title: "Inventory quantity differs between cart and order summary",
    description:
      "When two users add the last item at the same time, cart still shows available while order summary blocks checkout.",
    environment: "Staging",
    area: "Inventory",
    reporter: "Meera QA",
    logs: "stock_reservation conflict. retry_count=0. race condition suspected.",
  },
];

export const historicalDefects: HistoricalDefect[] = [
  {
    id: "PAY-1668",
    title: "Payment authorization timeout after OTP approval",
    description:
      "OTP success path intermittently returned 502 because payment provider reference was not persisted before authorization retry.",
    environment: "Production",
    area: "Payments",
    reporter: "Past QA",
    logs: "502 provider_ref missing authorize timeout",
    owner: "Payments Platform",
    severity: "Critical",
    priority: "P0",
    tags: ["payment", "otp", "gateway-timeout", "idempotency"],
    fixPattern: "Persist provider references before retrying authorization.",
    detectedSignals: ["502", "provider_ref missing", "checkout blocked"],
    lastSeen: "2026-07-12",
    resolution: "Added idempotency key and provider reference persistence.",
  },
  {
    id: "AUTH-640",
    title: "Safari reset token screen fails during crypto validation",
    description:
      "Safari did not support the crypto call used by reset token validation in the client bundle.",
    environment: "UAT",
    area: "Identity",
    reporter: "Past QA",
    logs: "crypto.subtle undefined safari reset token",
    owner: "Identity Services",
    severity: "High",
    priority: "P1",
    tags: ["identity", "safari", "password-reset", "browser-compatibility"],
    fixPattern: "Move sensitive token validation to server and add browser fallback.",
    detectedSignals: ["blank page", "Safari", "crypto.subtle undefined"],
    lastSeen: "2026-06-28",
    resolution: "Moved validation to server route and added browser fallback.",
  },
  {
    id: "ORD-917",
    title: "Race condition during final stock reservation",
    description:
      "Concurrent checkout attempts caused inconsistent cart and order summary stock states.",
    environment: "Staging",
    area: "Inventory",
    reporter: "Past QA",
    logs: "stock reservation conflict concurrency retry",
    owner: "Commerce Core",
    severity: "High",
    priority: "P1",
    tags: ["inventory", "race-condition", "stock-reservation", "checkout"],
    fixPattern: "Lock final reservation and retry transient conflicts.",
    detectedSignals: ["concurrent checkout", "reservation conflict", "quantity mismatch"],
    lastSeen: "2026-06-19",
    resolution: "Introduced reservation retry and locking around final quantity check.",
  },
  {
    id: "PAY-1532",
    title: "Checkout returns generic error when payment gateway is slow",
    description:
      "Gateway latency caused customer-facing generic errors instead of retryable payment states.",
    environment: "Production",
    area: "Payments",
    reporter: "Past QA",
    logs: "gateway timeout payment checkout error",
    owner: "Payments Platform",
    severity: "High",
    priority: "P1",
    tags: ["payment", "gateway-latency", "checkout", "retry-state"],
    fixPattern: "Classify gateway latency as retryable and preserve customer state.",
    detectedSignals: ["gateway timeout", "generic error", "checkout"],
    lastSeen: "2026-05-30",
    resolution: "Added provider timeout handling and customer retry state.",
  },
  {
    id: "AUTH-702",
    title: "Login session expires immediately after SSO callback",
    description:
      "Users are redirected back from SSO successfully but land on the login page because the session cookie is rejected.",
    environment: "Production",
    area: "Identity",
    reporter: "Past QA",
    logs: "Set-Cookie rejected SameSite=None Secure missing callback session invalid",
    owner: "Identity Services",
    severity: "Critical",
    priority: "P0",
    tags: ["identity", "sso", "cookie", "production-login"],
    fixPattern: "Apply secure cookie attributes consistently across callback domains.",
    detectedSignals: ["session invalid", "SSO callback", "cookie rejected"],
    lastSeen: "2026-07-02",
    resolution: "Updated cookie policy and added callback-domain regression coverage.",
  },
  {
    id: "ORD-1041",
    title: "Order confirmation email not sent after successful payment",
    description:
      "Orders are created and payment succeeds, but customers do not receive the confirmation email.",
    environment: "Production",
    area: "Orders",
    reporter: "Past QA",
    logs: "email_dispatch skipped order_created event missing correlation_id",
    owner: "Order Management",
    severity: "Medium",
    priority: "P2",
    tags: ["orders", "email", "eventing", "correlation-id"],
    fixPattern: "Guarantee order-created event metadata before dispatching notifications.",
    detectedSignals: ["email skipped", "event missing", "payment success"],
    lastSeen: "2026-05-18",
    resolution: "Added event metadata validation and replay job for missed notifications.",
  },
  {
    id: "SRCH-318",
    title: "Search results ignore brand filter after pagination",
    description:
      "Brand filter applies on the first page, but page two returns unfiltered results and incorrect counts.",
    environment: "UAT",
    area: "Search",
    reporter: "Past QA",
    logs: "query_state dropped filter=brand after cursor pagination",
    owner: "Experience Platform",
    severity: "Medium",
    priority: "P2",
    tags: ["search", "filter", "pagination", "query-state"],
    fixPattern: "Persist query filters inside pagination cursors.",
    detectedSignals: ["filter dropped", "cursor", "incorrect counts"],
    lastSeen: "2026-04-26",
    resolution: "Encoded active filters into the cursor token and added contract tests.",
  },
  {
    id: "INV-522",
    title: "Low-stock badge shows stale quantity after warehouse sync",
    description:
      "Warehouse sync updates actual inventory, but the storefront badge keeps the pre-sync quantity for several minutes.",
    environment: "Staging",
    area: "Inventory",
    reporter: "Past QA",
    logs: "cache ttl exceeded inventory_sync completed storefront_badge stale",
    owner: "Commerce Core",
    severity: "Low",
    priority: "P3",
    tags: ["inventory", "cache", "warehouse-sync", "storefront"],
    fixPattern: "Invalidate storefront inventory cache after warehouse sync completes.",
    detectedSignals: ["stale badge", "sync completed", "cache ttl"],
    lastSeen: "2026-03-14",
    resolution: "Added targeted cache invalidation from the inventory sync event.",
  },
  {
    id: "RPT-209",
    title: "Daily revenue report excludes refunded transactions",
    description:
      "Finance report total does not subtract partial refunds, creating a mismatch against payment settlement exports.",
    environment: "Production",
    area: "Orders",
    reporter: "Past QA",
    logs: "daily_revenue mismatch refund_adjustment not joined settlement export variance",
    owner: "Order Management",
    severity: "High",
    priority: "P1",
    tags: ["reporting", "refund", "finance", "settlement"],
    fixPattern: "Join refund adjustment ledger before report aggregation.",
    detectedSignals: ["settlement variance", "refund adjustment", "daily revenue"],
    lastSeen: "2026-06-03",
    resolution: "Updated aggregation query and backfilled seven days of finance reports.",
  },
  {
    id: "PAY-1775",
    title: "Partial refund creates duplicate adjustment record",
    description:
      "Retrying a partial refund after a timeout creates a second adjustment row with the same settlement id.",
    environment: "Production",
    area: "Payments",
    reporter: "Past QA",
    logs: "partial refund retry duplicate adjustment settlement_id repeated timeout",
    owner: "Payments Platform",
    severity: "Critical",
    priority: "P0",
    tags: ["payment", "refund", "idempotency", "settlement"],
    fixPattern: "Use settlement id and refund amount as an idempotency boundary.",
    detectedSignals: ["partial refund", "duplicate adjustment", "timeout retry"],
    lastSeen: "2026-07-20",
    resolution: "Added refund idempotency constraint and duplicate-adjustment cleanup.",
  },
];

export const sampleNewDefect: Defect = {
  id: "NEW-001",
  title: "Refund API returns 500 for partial refund after settlement",
  description:
    "Support team reports partial refunds fail for settled card transactions. Full refund works, but partial refund returns 500 and no adjustment record is created.",
  environment: "Production",
  area: "Payments",
  reporter: "Hackathon Demo",
  logs: "POST /refund/partial 500 settlement_id null adjustment_write_failed customer-impact high",
};
